spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: serj
    password: 1234
    # –ü—É–ª —Å–æ–µ–¥–∏–Ω–µ–Ω–∏–π (HikariCP - –ø–æ —É–º–æ–ª—á–∞–Ω–∏—é, –º–æ–∂–Ω–æ —É–∫–∞–∑–∞—Ç—å –Ω–∞—Å—Ç—Ä–æ–π–∫–∏ –ø—É–ª–∞)

logging:
  level:
    com.zaxxer.hikari: ERROR

app:
  notifications:
    templates:
      message: "–ö–∞–∂–µ—Ç—Å—è, –≤—ã —Å–æ–≤–∞ ü¶â"
      ticket: "–í—ã –ø—Ä–æ–µ—Ö–∞–ª–∏ —É–π–º—É –ø–æ–µ–∑–¥–æ–∫ –∑–∞ –ø–æ—Å–ª–µ–¥–Ω–∏–π –º–µ—Å—è—Ü üöå, —Å–ª–µ–¥—É—é—â–∞—è –ø–æ–µ–∑–¥–∫–∞ –±—É–¥–µ—Ç –±–µ—Å–ø–ª–∞—Ç–Ω–æ–π"
      coffee: "–ó–∞–º–µ—Ç–∏–ª–∏, –≤—ã —á–∞—Å—Ç–æ –ø–æ–∫—É–ø–∞–µ—Ç–µ –∫–æ—Ñ–µ –ø–æ –ø—è—Ç–Ω–∏—Ü–∞–º, —Å—Ä–µ–¥–∞–º –∏ –ø–æ–Ω–µ–¥–µ–ª—å–Ω–∏–∫–∞–º, –¥–µ—Ä–∂–∏—Ç–µ –∫—É–ø–æ–Ω –Ω–∞ —Å–∫–∏–¥–∫—É –≤–æ –≤—Ç–æ—Ä–Ω–∏–∫!"
      reminder: "–û—á–µ–Ω—å –Ω–∞–¥–µ—é—Å—å, —á—Ç–æ –≤—ã –ø–æ–º–Ω–∏—Ç–µ –¥–ª—è —á–µ–≥–æ –≤—ã –æ—Å—Ç–∞–≤–∏–ª–∏ —ç—Ç–æ –Ω–∞–ø–æ–º–∏–Ω–∞–Ω–∏–µ üòê"
      gym: "–í–∞—à–µ –∑–∞–Ω—è—Ç–∏–µ –¥–ª–∏–ª–æ—Å—å –∑–∞–º–µ—Ç–Ω–æ –¥–æ–ª—å—à–µ –ø—Ä–µ–¥—ã–¥—É—â–µ–≥–æ! –¢–∞–∫ –¥–µ—Ä–∂–∞—Ç—å! üí™"
  message:
    morningStart: 8
    nightStart: 22
    nightEnd: 6
  coffee:
    daysOfWeekToCheck: 1,3,5
    dayOfWeekOfDiscount: 2
  reminder:
    timeoutInSeconds: 60
  gym:
    timeoutInSeconds: 60
    minLessonDurationInMinutes: 10
    maxLessonDurationInMinutes: 120
    percentageDifferenceForNotification: 10
  ticket:
    monthlyTripsForDiscount: 10